# Site settings
title: Not So JUG
header-img: img/home-bg.jpg
#email: hello@davidmiller.io
description: "This is not a real Java User Group, just a bunch of Java enthusiasts who enjoy good design and code"
baseurl: ""
url: https://notsojug.github.io
#twitter_username: davidmillerskt
#github_username:  davidtmiller

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# Jekyll Redirect From Plugin for Redirects from Start Bootstrap Old Version
gems:
  - jekyll-paginate
